# CARTESIAN JOGGING THRESH
CART_JOG_X_THRESH_POSITIVE = 0.04
CART_JOG_X_THRESH_NEGATIVE = -0.03
CART_JOG_Y_THRESH_POSITIVE = 0.04
CART_JOG_Y_THRESH_NEGATIVE = -0.03
CART_JOG_Z_THRESH_POSITIVE = -0.21
CART_JOG_Z_THRESH_NEGATIVE = -0.2

# ROTATIONAL JOGGING THRESH
ROT_JOG_X_THRESH_POSITIVE = 0.13
ROT_JOG_X_THRESH_NEGATIVE = -0.2
ROT_JOG_Y_THRESH_POSITIVE = 0.2
ROT_JOG_Y_THRESH_NEGATIVE = -0.3
ROT_JOG_Z_THRESH_POSITIVE = 0.5
ROT_JOG_Z_THRESH_NEGATIVE = -0.5

MAX_FORCE_LIMIT = 20
MAX_TORQUE_LIMIT = 0.5

cart = (
    (CART_JOG_X_THRESH_POSITIVE, CART_JOG_X_THRESH_NEGATIVE),
    (CART_JOG_Y_THRESH_POSITIVE, CART_JOG_Y_THRESH_NEGATIVE),
    (CART_JOG_Z_THRESH_POSITIVE, CART_JOG_Z_THRESH_NEGATIVE),
)

rot = (
    (ROT_JOG_X_THRESH_POSITIVE, ROT_JOG_X_THRESH_NEGATIVE),
    (ROT_JOG_Y_THRESH_POSITIVE, ROT_JOG_Y_THRESH_NEGATIVE),
    (ROT_JOG_Z_THRESH_POSITIVE, ROT_JOG_Z_THRESH_NEGATIVE),
)


    